spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
# mysql 로 변경 필요
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug